### PR TITLE
Update library

### PR DESCRIPTION
**Pull request by EtienneMD**

### CODE REVIEW

**Comment by yp87** [comment]
We can merge this PR, but it will have no effect since this new commit only contains a new key and the key is already dynamically fetched from Tobias' repository.

**Comment by EtienneMD** [comment]
Problem must be one Nissan's side then because I have not been able to connect in about a week.

**Comment by yp87** [comment]
It is possible that they changed the key. If it is the case, it won't work until Tobias' update the repo with the new key.

**Comment by yp87** [comment]
I stopped using leaf2mqtt a few months ago. Instead, I use an old android phone + Tasker + autoinput + Join. 
Home assistant is interfacing with tasker on the phone through Join. Tasker will use autoinput to kill the Nissan Connect app, re-open it, login, refresh, read the values and send it to HomeAssistant using the REST api. There is also a task to sart charging and start climate. 

It is way more reliable than before

**Comment by jasrocha** [comment]
> I stopped using leaf2mqtt a few months ago. Instead, I use an old android phone + Tasker + autoinput + Join. Home assistant is interfacing with tasker on the phone through Join. Tasker will use autoinput to login to Nissan Connect app, refresh, read the values and send it to HomeAssistant using the REST api. There is also a task to sart charging and start climate.
> 
> It is way more reliable than before

Can You make a helper/tutorial how to make this?
Thanks.

**Pull request merged**
